---
# handlers file for wordpress
  - name: Start web server
    when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "Ubuntu" )
    systemd: 
      name: httpd 
      state: restarted
      enabled: true

  - name: Start DB server
    when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "Ubuntu" )
    systemd: 
      name: mariadb 
      state: restarted
      enabled: true