---
# tasks file for users/groups
  - name: Add user
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
    with_items:
    - new user


    
  - name: Ensure group "DevOps" exists
    ansible.builtin.group:
      name: "{{ item }}"
      state: present
    with_items:
    - DevOps